config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contacts, only: [ :new, :create ]
  resources :resume, only: [ :index ]
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :first_name, validate: true
  attribute :last_name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject, validate: true
  attribute :your_message, validate: true
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "ahlonko.kowouvi@gmail.com",
      :from => %("#{first_name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<div class="container d-flex align-items-center">
  <div class="row">
    <div class="col-12 col-lg-3 p-5">
      <h1><strong>Contact</strong></h1>
      <h4><strong>Phone</strong></h4>
      <p>+33 (0) 6 95 65 83 51</p>
      <h4><strong>Email</strong></h4>
      <p>ahlonko.kowouvi@gmail.com</p>
    </div>
    <div class="container col-12 col-lg-9 pt-5">
      <%= form_for @contact do |f| %>
        <div class="d-flex">
          <div class="container">
            <%= f.label :First_name %></br>
            <%= f.text_field  :first_name, required: true, class: "contact-form-text-area" %>
          </div>
          <div class="container">
            <%= f.label :last_name %></br>
            <%= f.text_field  :last_name, required: true, class: "contact-form-text-area" %>
          </div>
        </div></br>
        <div class="d-flex">
          <div class="container">
            <%= f.label :email %></br>
            <%= f.text_field :email, required: true, class: "contact-form-text-area" %>
          </div>
          <div class="container">
            <%= f.label :subject %></br>
            <%= f.text_field :subject, required: true, class: "contact-form-text-area" %>
          </div>
        </div></br>
        <div class="d-flex align-items-center">
          <div class="container">
            <%= f.label :your_message %></br>
            <%= f.text_area :your_message, rows: 8, cols: 40, required: true, class: "contact-form-text-area"%>
          </div>
          <div class="container">
          <%= f.submit 'Send', class: 'cta' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ahk</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <br>
      <% flash.each do |key, message| %>
        <p class="alert alert-<%= key %>"><%= message %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container d-flex p-5">
  <div class="row">
    <div class="col-12 col-lg-3">
      <img src="https://kitt.lewagon.com/placeholder/users/Ahlonko1" alt="logo">
    </div>
    <div class="col-12 col-lg-9">
      <h1><strong>Hello</strong></h1>
      <h3><strong>Who am I?</strong></h3>
      <p>What makes me as happy as Larry? When my code works!!</p>
      <p>After 8 years in Accounting, Tax and Finance,
      I recently endeavoured in the tech world by following the Web development bootcamp at Le Wagon and enjoyed it!
      Indeed coding suits my analytical background and my thirst to always keep learning as well as triggering my inner creativity.</p>
      <p>My previous experiences have provided me with the abilities to prioritize tasks and work on multiple assignments at the same time.
      I have also demonstrated adaptability in international environments and shown solid managerial skills.</p>
      <p>Today, I have SQL, Ruby, Ruby on Rails, Bootstrap, CSS, HTML, Git/Github and JavaScript under my belt.
      I am therefore looking for any challenging opportunity that will help my next professional chapter start with a bang.</p>
      <p>Feel free to reach out to me.</p>

      <div class="d-flex justify-content-around">
        <%= link_to resume_index_path do %>
          <button class="cta">
            <h5>Resume</h5>
          </button>
        <% end %>
        <%= link_to projects_path do %>
          <button class="cta">
            <h5>Projects</h5>
          </button>
        <% end %>
        <%= link_to new_contact_path do %>
          <button class="cta">
            <h5>Contact</h5>
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>
<a href="http://www.scubalibre.io" target="_blank">Go to Scuba Libre's website</a>

app/views/resume/index.html.erb
<h1>Resume</h1>
<div class="row">
  <div class="col px-5">
    <div>
    <h3>EDUCATION AND QUALIFICATIONS</h3>
    <div>
      <p><strong>Le Wagon, Paris</strong> - 9-week Web Development Full Stack bootcamp</p>
      <p><strong>AUDENCIA Business School, Nantes</strong> - Master double degree in Accounting and Finance</p>
      <p><strong>IAE School of Management, Lyon</strong> - Bachelor’s degree in Business Administration</p>
    </div>
    <h3>SKILLS</h3>
      <p><strong>LANGUAGES</strong></p>
      <p>FRENCH & ENGLISH: bilingual</p>
      <p>GERMAN: conversational</p>
      <p><strong>IT</strong></p>
      <p>ACCOUNTING: CEGID, SAGE, M3</p>
      <p>PROGRAMMING: Ruby on Rails, HTML, CSS, JavaScript, SQL, Bootstrap, Regex, Heroku</p>
      <p>VERSIONING: Git, GitHub</p>
    <h3>ACTIVITIES AND INTERESTS</h3>
      <p><strong>SPORTS</strong></p>
      <p><strong>CULTURE</strong></p>
    </div>
  </div>
  <div class="col">
    <div>
      <h3>WORK EXPERIENCE</h3>
      <p><strong>Flexstone Partners, Paris</strong> - Middle Office Manager – Full time</p>
      <p><strong>EY, Paris</strong> - Manager FSO (Financial Services Office) - TAX department – Full time</p>
      <p><strong>Grant Thornton, Paris</strong> - Senior Associate - IBAS department – 6-month internship then Full time</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light">
  <div class="navbar-collapse">
    <div class="name">
      Ahlonko
    </div>
    <div class="logo">
      <%= link_to root_path, class:"text-decoration-none" do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
      <a href="https://github.com/Ahlonko1" target="_blank"><i class="fa-brands fa-github"></i></a>
      <a href="https://www.linkedin.com/in/ahlonkokowouvi/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
    </div>
  </div>
</nav>